/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rest2_jni_ActiveDispatcher */

#ifndef _Included_com_rest2_jni_ActiveDispatcher
#define _Included_com_rest2_jni_ActiveDispatcher
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rest2_jni_ActiveDispatcher
 * Method:    createRecords
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rest2_jni_ActiveDispatcher_createRecords
  (JNIEnv *, jobject, jstring jquery);

/*
 * Class:     com_rest2_jni_ActiveDispatcher
 * Method:    getRecord
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rest2_jni_ActiveDispatcher_getRecord
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_rest2_jni_ActiveDispatcher
 * Method:    getAllRecords
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rest2_jni_ActiveDispatcher_getAllRecords
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
